package com.dxy.phonefraud.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dxy.phonefraud.greendao.FraudSms;
import com.dxy.phonefraud.greendao.FraudPhone;

import com.dxy.phonefraud.greendao.FraudSmsDao;
import com.dxy.phonefraud.greendao.FraudPhoneDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fraudSmsDaoConfig;
    private final DaoConfig fraudPhoneDaoConfig;

    private final FraudSmsDao fraudSmsDao;
    private final FraudPhoneDao fraudPhoneDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fraudSmsDaoConfig = daoConfigMap.get(FraudSmsDao.class).clone();
        fraudSmsDaoConfig.initIdentityScope(type);

        fraudPhoneDaoConfig = daoConfigMap.get(FraudPhoneDao.class).clone();
        fraudPhoneDaoConfig.initIdentityScope(type);

        fraudSmsDao = new FraudSmsDao(fraudSmsDaoConfig, this);
        fraudPhoneDao = new FraudPhoneDao(fraudPhoneDaoConfig, this);

        registerDao(FraudSms.class, fraudSmsDao);
        registerDao(FraudPhone.class, fraudPhoneDao);
    }
    
    public void clear() {
        fraudSmsDaoConfig.clearIdentityScope();
        fraudPhoneDaoConfig.clearIdentityScope();
    }

    public FraudSmsDao getFraudSmsDao() {
        return fraudSmsDao;
    }

    public FraudPhoneDao getFraudPhoneDao() {
        return fraudPhoneDao;
    }

}
